name: two jobs in sequence Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print job details
        run: echo "This is first job."
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: print job details
        run: echo "This is second job."
